/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.chamerling.ow2con.services.crisis;

import itemis.demo.sprinkler.Sprinkler;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0 2011-11-23T09:34:40.570+01:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(serviceName = "SprinklerService", portName = "SprinklerPort", targetNamespace = "http://demo.itemis/Sprinkler", endpointInterface = "itemis.demo.sprinkler.Sprinkler")
public class SprinklerImpl implements Sprinkler {

	boolean start = false;
	private static final Logger LOG = Logger.getLogger(SprinklerImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see itemis.demo.sprinkler.Sprinkler#start(*
	 */
	public void start() {
		System.out.println("Executing operation start");
		try {
			start = true;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see itemis.demo.sprinkler.Sprinkler#isStarted(*
	 */
	public boolean isStarted() {
		System.out.println("Executing operation isStarted");
		try {
			return start;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see itemis.demo.sprinkler.Sprinkler#stop(*
	 */
	public void stop() {
		LOG.info("Executing operation stop");
		try {
			start = false;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
