/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.chamerling.ow2con.services.crisis;

import itemis.demo.statuslistener.StatusListener;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.0 2011-11-23T09:34:40.864+01:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(serviceName = "StatusListenerService", portName = "StatusListenerPort", targetNamespace = "http://demo.itemis/StatusListener", endpointInterface = "itemis.demo.statuslistener.StatusListener")
public class StatusListenerImpl implements StatusListener {

	private static final Logger LOG = Logger.getLogger(StatusListenerImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see itemis.demo.statuslistener.StatusListener#notifyStatus(itemis.demo.
	 * statuslistener.Status status )*
	 */
	public void notifyStatus(itemis.demo.statuslistener.Status status) {
		System.out.println("Executing operation notifyStatus");
		System.out.println(status);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
