
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.chamerling.ow2con.service.hotel;

import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import petals.ow2.org.demo.travelagency.hotel.Hotel;
import petals.ow2.org.demo.travelagency.hotel.HotelResponse;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-11-21T16:03:07.192+01:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "hotel",
                      portName = "hotelSOAP",
                      targetNamespace = "http://org.ow2.petals/demo/travelagency/hotel/",
                      endpointInterface = "petals.ow2.org.demo.travelagency.hotel.Hotel")
public class HotelService implements Hotel {
	
	private static final AtomicLong al = new AtomicLong(0);

    /* (non-Javadoc)
     * @see petals.ow2.org.demo.travelagency.hotel.Hotel#bookRoom(java.lang.String  lastname ,)java.lang.String  firstname ,)java.lang.String  address ,)javax.xml.datatype.XMLGregorianCalendar  date )*
     */
    public petals.ow2.org.demo.travelagency.hotel.HotelResponse bookRoom(java.lang.String lastname,java.lang.String firstname,java.lang.String address,javax.xml.datatype.XMLGregorianCalendar date) { 
        System.out.println("Executing operation bookRoom");
        System.out.println(lastname);
        System.out.println(firstname);
        System.out.println(address);
        System.out.println(date);
        try {
        	HotelResponse response = new HotelResponse();
        	response.setFirstname(firstname);
        	response.setLastname(lastname);
        	response.setReservationId(al.incrementAndGet());
        	response.setValidated(true);
            return response;
            
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
